# Generated by Django 3.0.1 on 2020-01-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0004_auto_20200116_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='negative',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='neutral',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='positive',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
    ]
