# Generated by Django 3.0.1 on 2020-01-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0005_auto_20200116_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='negative',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='neutral',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='positive',
            field=models.CharField(max_length=100),
        ),
    ]
