# Generated by Django 3.0.1 on 2020-01-16 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0007_auto_20200116_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='overall_rating1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('process_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.FloatField(default=0.0)),
                ('positive', models.FloatField()),
                ('negative', models.FloatField()),
                ('neutral', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Filedata',
        ),
    ]
